### PR TITLE
Entity and effect cleanup for better GC

### PR DESCRIPTION
**Pull request by dlamkins**
Implemented `IDisposable` on all entities.  Began sharing most `Effect` instances to reduce overhead.

### CODE REVIEW

**Review by greaka — APPROVED** [review]

**Review by greaka — APPROVED** [review]

**Comment by dlamkins** [comment]
@greaka This was originally intended to be put in as a draft.  I think I clicked the wrong thing when I submitted it, though.  Is there a way to switch it back to a draft?

**Comment by greaka** [comment]
I know of no way, sry 🙁

**Comment by dlamkins** [comment]
~~Okay, this is ready for review now.~~

Let me review my implementation once more.  I may be locking the poor GC out of collecting my disposed objects.

Can confirm: I missed putting the finalizers on them somehow.  Will update again once ready.

**Review by nickcode122 — APPROVED** [review]

**Comment by dlamkins** [comment]
Okay, I did additional research pretty in-depth as I wasn't feeling 100% about my implementation and found that it's not as hard as I was making it and that I had some misconceptions, so I'm going to put those changes in place tomorrow and push after doing some additional profiling to confirm everything is ready.

**Comment by dlamkins** [comment]
Going to close this for now.  Lots of changes have been made and I'll need to seperate them out into more siloed PRs.

**Pull request closed without merging**
