### PR TITLE
include_wikimedia_lib_to_support_wiki_searching_in_universal_search

### PR DESCRIPTION
**Pull request by bennieboj**
include_wikimedia_lib_to_support_wiki_searching_in_universal_search
needed for this PR: https://github.com/blish-hud/Community-Module-Pack/pull/66

### CODE REVIEW

**Comment by dlamkins** [comment]
Thanks!  Is there a reason why the reference can't get included directly in that module instead of needing to include it directly here in core?

**Comment by bennieboj** [comment]
I did include it in the module, but that didn't work for some reason when running blish. Should this work? I noticed that other dependencies were also both in the module and in the core? I can remove it again and test if your want.

**Comment by dlamkins** [comment]
Some of the dependencies are still in core since the modules used to actually get compiled as just classes directly within the main assembly.  We're slowly getting some of that out.

If the module project is still using Fody for dependency merging, that may be the issue.  Modules now support including DLL dependencies from NuGet or otherwise which can be loaded from their .bhm.  Those should get packaged up automatically if compiled normally.

I'm not going to make you try and guess and find out what it is, though.  I'll go over and poke at it some and see if I can get it to include the dependency correctly.  🙂

**Comment by bennieboj** [comment]
Great, thanks for the help 😁

**Comment by dlamkins** [comment]
Alright, between the semi-recent improvements to dependency loading for modules and https://github.com/blish-hud/Blish-HUD/pull/345 which is currently pending approval, the change here should no longer be necessary and should be able to get fully included in https://github.com/blish-hud/Community-Module-Pack/pull/66/commits/01a36b16becaa0e7e9deeb4af848937f2d30c7c4

**Comment by bennieboj** [comment]
K, I subbed to #345  and will try to test once it's merged to develop

**Comment by dlamkins** [comment]
Sorry for keeping this open for so long.  Was keeping it open as a reminder.  Gonna go ahead and close and review it again on the module side.  Thanks again!

**Pull request closed without merging**
