### PR TITLE
HorizontalAlignment.Right & .Center for TextBox

### PR DESCRIPTION
**Pull request by agaertner**
Custom HorizontalAlignment for TextBox.

Currently just for the single line TextBox. 
Eventually cool to have for MultiLineTextBox as well, but a bit trickier to implement (recalculation of highlightregion etc).

Preview: https://i.imgur.com/DUQt0lB.gif

### CODE REVIEW

**Comment by dlamkins** [comment]
If it's gonna be exposed publicly on the base class but not implemented in the multiline one yet, I don't think we can leave it only implemented on the standard textbox.

I think I'd prefer the property and its implementation remain in the standard textbox control - i.e. not in the base input control class.  I don't see an immediate use case for horizontal alignment for the multi-line box (outside of RTL, which this really isn't a solution for and kind of ambitious for Blish HUD).

If it becomes difficult to implement that way, you could perhaps include the horizontal alignment as a parameter in the call to draw text and have it default left side or something.

Let me know your thoughts.

**Comment by dlamkins** [comment]
An aside, but wanted to mention it looks really good in that book UI demo you showed.

**Comment by agaertner** [comment]
> If it's gonna be exposed publicly on the base class but not implemented in the multiline one yet, I don't think we can leave it only implemented on the standard textbox.
> 
> I think I'd prefer the property and its implementation remain in the standard textbox control - i.e. not in the base input control class. I don't see an immediate use case for horizontal alignment for the multi-line box (outside of RTL, which this really isn't a solution for and kind of ambitious for Blish HUD).
> 
> If it becomes difficult to implement that way, you could perhaps include the horizontal alignment as a parameter in the call to draw text and have it default left side or something.
> 
> Let me know your thoughts.

I had that thought as well. It's all in the TextBox class now.

**Comment by dlamkins** [comment]
Looks great!

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
