### PR TITLE
Removed Musician assets, added new Book and Page controls, and added NewKrytan font.

### PR DESCRIPTION
**Pull request by TybaIt**
Added ./Controls/BasicWindow.cs, 
Added ./Controls/Book.cs
Added ./Controls/Page.cs
Removed Musician assets from ref/
Added newkrytan-12-regular bitmapfont files to MonoGame Pipeline. (./Content/fonts/newkrytan/)

### CODE REVIEW

**Comment by greaka** [comment]
can you please make a different pr for the new krytan, windows and controls stuff? It is easier to review

**Comment by TybaIt** [comment]
not this time. Sorry. I just added them but I will be working on them further. 
How does your review process look anyway? Are you using some technology to review that makes it hard when its not separate?

**Comment by greaka** [comment]
why not?

**Comment by TybaIt** [comment]
Things to review:

https://github.com/TybaIt/Blish-HUD/blob/dev/Blish%20HUD/Controls/Book.cs
https://github.com/TybaIt/Blish-HUD/blob/dev/Blish%20HUD/Controls/Page.cs
https://github.com/TybaIt/Blish-HUD/blob/dev/Blish%20HUD/Controls/BasicWindow.cs

**Comment by TybaIt** [comment]
I've added simple TODO's where the book sound assets need to be played in Book.cs @dlamkins

**Pull request merged**
