### PR TITLE
WIP: Multibox Support

### PR DESCRIPTION
**Pull request by dlamkins**
Early draft of multibox support.

- Need to find a way for the ArcDps to either handle multiple instances or have it gracefully not start if there is already an instance listening.

### CODE REVIEW

**Comment by greaka** [comment]
Just curious, what is still missing here?

**Comment by dlamkins** [comment]
https://discordapp.com/channels/531175899588984842/536970543736291346/715928883400147065

> Eh, just one or two to clean up the method used to resnap (it'll show on the first proc at launch until you click into the GW2 window it'll end up being assigned to - doesn't cause any problems, but I can at least make it slightly cleaner).

**Comment by dlamkins** [comment]
Working on this now.

**Comment by dlamkins** [comment]
Closed in favor of #247

**Pull request closed without merging**
