### PR TITLE
Sync taskbar icon with game running

### PR DESCRIPTION
**Pull request by entrhopi**
Proposal for #504
It has quite a significant delay since `Gw2InstanceIntegration` is not very fast hooking onto the game

### CODE REVIEW

**Comment by entrhopi** [comment]
Minimizing of the game is not handled yet.

**Comment by dlamkins** [comment]
This will be very great.  😄

Oh, nice.  Is there any issue calling `SetShowInTaskbar` to the same value?  That is to say, can this be made more stateless by removing that `_inTaskbar` var?

Something else to consider is that we now also restart Blish HUD when the game is closed, so likely at most we'd only ever need to toggle the taskbar item on, once, when the game is first detected since the moment the game is no longer running, we just restart Blish HUD and can default to it not being visible again until the game is detected.  🤔

**Comment by entrhopi** [comment]
> Oh, nice. Is there any issue calling `SetShowInTaskbar` to the same value? That is to say, can this be made more stateless by removing that `_inTaskbar` var?
> 
> Something else to consider is that we now also restart Blish HUD when the game is closed, so likely at most we'd only ever need to toggle the taskbar item on, once, when the game is first detected since the moment the game is no longer running, we just restart Blish HUD and can default to it not being visible again until the game is detected. 🤔

Ah nice, I was wondering about that. Thanks for the input!
In that case we should in fact be able to skip `_inTaskbar`, I'll refactor this and run some tests.

**Comment by dlamkins** [comment]
Great!

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
